### ISSUE TITLE
TAX-MK-AUTOMATION USE CASE - TAX FORM 1042

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#15]

**Comment by Sathraja-Beez** [comment]
Waiting for client regarding some solution clarifications to proceed with pdd

**Comment by Sathraja-Beez** [comment]
On hold since there were other high priority use cases

**Comment by mbm-hub** [comment]
This use case is cancelled by OPEX team as it identified as yearly run and generating less value for automation.
