### ISSUE TITLE
PDF read data using Java library

### ISSUE THREAD

**Issue by Dean13b** [beezlabs-org/automation-dev#175]

**Comment by Dean13b** [comment]
@AnanthaKrishnan3646 , please check for library support to read data from PDF document using JAVA

**Comment by AnanthaKrishnan3646** [comment]
Had a discussion with @karthikeyan23  and @stsfaroz and could see that the data in the PDF are in an image format which cannot be obtained using open source libraries from both java and python and as an alternate it can be done by using Azure Service , OpenAI GPT-4 and also In-house models. However, the volumes of the documents are a dependency for this approach.
