### ISSUE TITLE
Tesco Portal Change Analysis

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/automation-dev#186]
We have observed some change in the Tesco portal due to which the automation has failed for current month run. Need further analysis.

**Comment by Sakthi1502** [comment]
PDD Link: https://azurebeezlabs.sharepoint.com/:f:/s/BeezLibrary/EkLsOAlb7_NHkt_QlmbTMS4BsMQMv4G1Qg9zrrBY3s8cQQ?e=GYLDhe

**Comment by Sakthi1502** [comment]
@Dean13b We need to analyze this issue further which is failing in Production and based on the efforts estimation by the developer we will seek management's approval to proceed with changes. Wish to allocate @NaveenKumarD8 on the same.

**Comment by koushik-ac** [comment]
@NaveenKumarD8 is not able to analyse this issue as he is not able to access the Portal because of Password expiry. @Sakthi1502 to connect with client to get new password.

**Comment by Sakthi1502** [comment]
Update: Updated credentials shared with via email to the developer. FYI @NaveenKumarD8

**Comment by Sakthi1502** [comment]
@NaveenKumarD8 Please update on the analysis and effort needed to fix the changes here.

**Comment by NaveenKumarD8** [comment]
I have analyzed the site the resumbit button has been changed.
It takes one day time effort to fix it.

**Comment by Sakthi1502** [comment]
The effort of one day has been approved and we need some one allocated to work on the change. FYI @Dean13b

**Comment by NaveenKumarD8** [comment]
The changes have been made and all Xpaths changed into constant and the Bot Tested in Tulip.

**Comment by Sakthi1502** [comment]
We have made the production run after the fixes done. Closing this issue.
