### ISSUE TITLE
JULY'23_SEA HQ_ Intercompany recharge :Q1 (NO.3) #2855624

### ISSUE THREAD

**Issue by AshwinPS-BZ** [beezlabs-org/automation-dev#189]
Creating this issue to check on the MJE ticket and fix it.

**Comment by AshwinPS-BZ** [comment]
I'll start with the analysis and fixes from tomorrow (14/12/23).

**Comment by AshwinPS-BZ** [comment]
I need more information from the users to continue the analysis. This has been communicated to the helpdesk team.

**Comment by koushik-ac** [comment]
@AshwinPS-BZ received additional documentation. He will be starting the analysis from today.

**Comment by AshwinPS-BZ** [comment]
We are still awaiting client response on this as confirmed by the Support team.

**Comment by AshwinPS-BZ** [comment]
the SysAid #2855624 is closed as the users are not going ahead with the enhancement we suggested.
