### ISSUE TITLE
General Ledger ZDUMMY Project

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#19]
Reclass of documents without profit center in SAP due to pending information at the moment of the entry.

**Comment by mbm-hub** [comment]
Need to re-estimate @mbm-hub ; To be split into two automations; FS to be prepared and sent @koushik-ac

**Comment by mbm-hub** [comment]
Dependency: Create an NC @mbm-hub

**Comment by mbm-hub** [comment]
Dependency: Category , sub-category details to be identified with customer for Proposal creation

**Comment by Sathraja-Beez** [comment]
Testing will be completed by Feb 23,23

**Comment by Sathraja-Beez** [comment]
UAT on Feb 23 ,2023

**Comment by Sathraja-Beez** [comment]
UAT started on Feb 23 and will continue  till March 03

**Comment by mbm-hub** [comment]
Fixes are completed and test document is shared with the end user for UAT sign-off.

FS Approval to be requested to Luciano by 23-Mar

Security approval procured.

Scope list and RICEF list to be updated. Bharath to provide FIRE ID / RICEF ID.

CAB Approval to be procured. Bharath to discuss with Juan on BES call today.

**Comment by mbm-hub** [comment]
A small fix on company code leading 0 is pending. UAT sign-off pending. ETA 28-March.

FS, TS approval procured. Go-Live preparations are all ready.

**Comment by Sathraja-Beez** [comment]
Sent for fasttrack approval , Planning to go to prod this week
