### ISSUE TITLE
Alberta Virginia STO Automation

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#22]

**Comment by mbm-hub** [comment]
Dependency with Diana on Distribution channel logic.
@mbm-hub / @Dean13b to setup a call this week and close the discussion

**Comment by mbm-hub** [comment]
UAT sign-off planned for 6-Feb by @Dean13b 
Go-Live and dependency to be escalated to Adriana by @mbm-hub

**Comment by mbm-hub** [comment]
UAT call with Manuel and Adriana happened today for Alberta. (Virginia was already completed with Sander in the past).
Once we get sign-off from Manuel by 7-Feb, billing has to be planned.

**Comment by mbm-hub** [comment]
Distribution channel logic is escalated to Juan for the stakeholder misalignment happening. Will be discussed on checkpoint call on Tuesday (7-Feb). This is not considered as a UAT obligation.

**Comment by mbm-hub** [comment]
Preparation of FS/TS is assigned to @AshwinPS-BZ  by @Dean13b

**Comment by Sathraja-Beez** [comment]
Going live this week.

**Comment by mbm-hub** [comment]
Virginia is LIVE.

Alberta, rule mapping is Pending, ETA is 27-March.
