### ISSUE TITLE
Canada Automation Initiative

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#25]

**Comment by mbm-hub** [comment]
Latest update: Requirement call setup with Joy and Shweta on 12-Jan

**Comment by Sakthi1502** [comment]
@dominicceo @mbm-hub Please find the latest update regarding Canada Automation based on the last call on 12th Jan.
1) We have got the requirements for 1 Portal - https://www.bcliquorstores.com/ which is an e-commerce portal and only prices are needed to be extracted according to pre-configured SKUs. We are waiting for some clarifications for this portal which I will do a follow up today.
2) Requirements for remaining 5 Retailer Portal to be available in last week of January/first week of February. 
3) Customer has asked whether we can start with Bcliquorstores and take the remaining portals later. @dominicceo @mbm-hub to confirm.

**Comment by dominicceo** [comment]
Please give us the complexity and Bharath should mix this with the existing SOW for minibar and then we are good to go to commence this once we have the approval

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sakthi1502** [comment]
Hi @dominicceo @mbm-hub Please find the points below for Bcliquorstores ( 1 Site given to us till now) regarding effort estimation.
1) Assessment + PDD Preparation - 1 Working Day
2) Development, Testing and Deployment - 5 Working Days

**Comment by Sathraja-Beez** [comment]
Development starts from Wednesday ,and require 5 business days

**Comment by Sakthi1502** [comment]
Update (02/02/2023): Had a call with Shweta and insisted on the other 5 retailor sites for us to start analysis and development. She is currently not sure when we would receive the info regarding 5 other retailor sites. However, she has confirmed she has the PO ready and share it with us shortly.

**Comment by mbm-hub** [comment]
New websites (5) received on 10-Feb. @Sakthi1502 to come up with a PDD for the same

**Comment by Sakthi1502** [comment]
Update(16/02/2023): We need some requirement clarifications on the latest 5 websites shared. We have done the analysis of the 5 websites. Have asked for time with customer tomorrow (17/02/2023) for requirement clarifications.

**Comment by Sakthi1502** [comment]
Dependency for Sharepoint Download: We need credentials to use graph api approach for accessing bacardi sharepoint since the input files for all the 6 Websites are hosted in bacardi sharepoint. cc: @mbm-hub

**Comment by Sathraja-Beez** [comment]
In Process of finalizing the approach with the guidance from Karthick  (any alteration from PO)

**Comment by mbm-hub** [comment]
BCliquors output format to be chagned to xlsx. Need to check if @Sakthi1502 can take it up.

**Comment by Sathraja-Beez** [comment]
We have agreed with customer that the data for all 6 retailors to be provided on 20th of every month. The data for all 6 retailors to be made available by 7pm IST for client's consumption in production azure.

**Comment by mbm-hub** [comment]
@Sakthi1502 , what is still pending for us to keep this active?
Is it the automation workflow deployments and schedule them? Please confirm.
If that is done, close this task and keep the board updated with open items alone.

**Comment by Sakthi1502** [comment]
@mbm-hub Canada Automation Initiative is yet to go live. We haven't done any bots or configured any workflows till now. We are just supplying data to customer as of now.

**Comment by Sathraja-Beez** [comment]
@anandamurugan36 is working on it and ETA – this week

**Comment by kruthik-nivas** [comment]
All the workflows are done and files for this month have been submitted, this can be closed
