### ISSUE TITLE
Open Commitments

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#27]
Extraction of SAP report from <TCODE> and uploading the files to SharePoint site.

- [x] PDD
- [x] Development
- [x] SIT
- [x] UAT
- [x] SharePoint App dependency
- [x] ADLS directories to be collected
- [x] Regression testing
- [x] Deployment

**Comment by Sathraja-Beez** [comment]
PPD Was done & assiged to @Avishikta1200

**Comment by mbm-hub** [comment]
Check on the app@sharepoint details. @Dean13b  to confirm

**Comment by mbm-hub** [comment]
Bot registration is not happening. @kruthik-nivas to help

**Comment by mbm-hub** [comment]
RPA Hive dependency is there. @Kalidass2011 to check.
@mbm-hub to check with Chris Marshall for getting app created

**Comment by Sathraja-Beez** [comment]
Development was done , following up for Azure app to start testing . Expected date to complete this 13-April

**Comment by mbm-hub** [comment]
122d7567-5f65-447e-abeb-76cf26d12c2d is the siteId for production sharepoint site. @kruthik-nivas @koushik-ac @Rupsa96 / FYI

**Comment by koushik-ac** [comment]
We have received Permissions from security team for Azure App. We were able to perform initial testing to check if the App is able to access the site or not, it was successful. @Rupsa96 to confirm if the end-to-end testing is complete or not.

**Comment by kruthik-nivas** [comment]
We were not able to fetch the drive id folder id , From factory side we have requested this to consultants

**Comment by mbm-hub** [comment]
Dependency of access is till open, it has to be solved with Levi's counterpart by 15/16 May.
A new folder creation is suggested to solve the PBI connectivity issues. Koushik to talk to Juan on this today and get the needs done.
RPA regression to be done - Variations to be identified with Dinesh, Sakthi.
ETA for go-live 18-May.

**Comment by kruthik-nivas** [comment]
The new Approach PDD with test cases has been received from consultants, @anandamurugan36  has to create a developer document based on which developers will develop and submit their test cases. Once the developer document is done @anandamurugan36  will provide an ETA for this project

**Comment by mbm-hub** [comment]
- Demo was given to customer on the ADLS approach on May 29
- Files are validated by David and confirmed that they can read it fine
- As next step, PTP team will connect these files to BI dashboard and validate the data

- There is code enhancement to be done for handling large files at DMS activity. @anandamurugan36 was made responsible to address this issue.
- Go-live was suggested to proceed from other business needs, the above enhancement is to be addressed over a course of time, @koushik-ac @anandamurugan36  to come up with a plan/timeline.

**Comment by mbm-hub** [comment]
Automation schedule has to be finalized. @koushik-ac @mbm-hub to discuss.

**Comment by mbm-hub** [comment]
Automation is LIVE
