### ISSUE TITLE
Intercoprice Automation

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#33]

**Comment by Sathraja-Beez** [comment]
Factory team should provide a resource to work on these

**Comment by Sathraja-Beez** [comment]
@AmitRanjanBasu will be completing the development by Mar 30 , can be deprioritized as well for NTT Go-live

**Comment by Sathraja-Beez** [comment]
UAT was planned on coming Tuesday (11 April)

**Comment by Sathraja-Beez** [comment]
Development was done by @AmitRanjanBasu  , Call  scheduled for tomorrow (11 April) to give demo and handover  for UAT

**Comment by mbm-hub** [comment]
Development handover is completed to Consultant.
SIT Testing is pending, sharepoint access was pending as an issue which is resolved now.
SIT to start from Consultant and plan for UAT handover by 21 April.

Cc: @koushik-ac

**Comment by Sathraja-Beez** [comment]
Got UAT Signoff , planning for deploying into prod
