### ISSUE TITLE
Costco Enhancement

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#40]

**Comment by Sakthi1502** [comment]
@mbm-hub @Sathraja-Beez  We need to know if we have the approval to commence this project based on the efforts provided. Based on your confirmation, I can send the PDD to client to get a requirement signoff.

**Comment by Sakthi1502** [comment]
Hi @mbm-hub @Sathraja-Beez I have the pdd ready with me after the required clarifications we obtained with client. Wish to send the same to client for a confirmation over email and then I can handover to the factory team. Kindly confirm

**Comment by Sathraja-Beez** [comment]
Check point call  at April 26

**Comment by mbm-hub** [comment]
File has been shared to Customer, need to get sign-off.
