### ISSUE TITLE
Web Scraping - Minibar Platform

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#5]
Consultant: Sakthivel

PDD Attached:

https://azurebeezlabs.sharepoint.com/:w:/s/BeezLabsFactory/EeMcM_RjVBZLudKwg8BQh_8Br7s-lAGoejmaVtQVnoUQSA?e=BK3scB

**Comment by Sathraja-Beez** [comment]
Waiting to get approval for UAT

**Comment by Sakthi1502** [comment]
We have run the automation and pushed the file to Prod Azure path given by the client on 24/01/2023.
