### ISSUE TITLE
DutyfreeAmerica Development

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/automation-dev#58]

**Comment by Sakthi1502** [comment]
R&D in progress as of now. Once the results of R&D are finalized which probably will be done early next week, development will commence.

**Comment by karthikeyan23** [comment]
Rupsa is leave today, we shall discuss this tomorrow

**Comment by karthikeyan23** [comment]
Extraction is completed for 40 stores out of 42 stores. The output has to be converted from the current json to csv (tentative on Monday).

**Comment by karthikeyan23** [comment]
the data for 40 sites to be completed by today

**Comment by Dean13b** [comment]
Files for 40 sites shared to Sakthi. And Sakthi has given some enhancement to be done. Rupsa is working on that.

**Comment by Sakthi1502** [comment]
Update: For some of the products, quantity can be extracted from url. This is being asked to be implemented in solution. The url links were throwing bad gateway error yesterday. Rupsa to check and highlight if any issues are being faced by her today and continue with changes.

**Comment by koushik-ac** [comment]
40 Stores files have been submitted by Rupsa and this has been verified by Sakthi. Rupsa is working on the remaining two stores.

**Comment by Sakthi1502** [comment]
@karthikeyan23 The issue regarding data extraction for other stores has been resolved by @Rupsa96. The file has been generated and sent to client for review.

**Comment by Sakthi1502** [comment]
Update: Client has highlighted a formatting issue in data. Rupsa has been asked to check. Once the issue is corrected, we will resend the file for UAT

**Comment by karthikeyan23** [comment]
@Rupsa96  once you complete it, as discussed plan for a session with the entire team to share your learnings

**Comment by Sakthi1502** [comment]
@karthikeyan23 Wish to convey that the changes has been completed by @Rupsa96. We have sent the file again to client for review.

**Comment by Sakthi1502** [comment]
Update: Date Format Issue has been raised by customer which has been communicated to @Rupsa96 to be checked on priority since we are planning to get a signoff today.
