### ISSUE TITLE
G/L Clearing (VAT) Enhancements

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#6]
Consultant: Koushik

Documentation:

**Comment by mbm-hub** [comment]
Agreed to have less dependency with Nivas on this item and see who else can be assigned. @karthikeyan23  to confirm.

**Comment by mbm-hub** [comment]
New change requested for Cockpit Proposal integration to be discussed and agreed on an approach and share the estimates to Juan if any additional efforts required.

**Comment by mbm-hub** [comment]
@koushik-ac to get the test data from Luciano/Marcela, or be prepared with test data.

**Comment by Sathraja-Beez** [comment]
Business user is on leave till FEB 27 , we need to have UAT call post that by Feb 28

**Comment by mbm-hub** [comment]
1. Excel Attachment to be made available on the task. We agreed on the consolidated excel as attachment.
2. Approval matrix is pending to be included for task creation based on clearing amount
3. Body of the email to be updated with the clearing status

**Comment by mbm-hub** [comment]
Unit test document preparation is happening for requesting UAT sign-off.

FS approval and Security approval are already procured.

**Comment by Sathraja-Beez** [comment]
We are waiting for the end-users to perform additional testing of the solution and provide us with the UAT approval. Once we receive this approval, we will move the solution to Production. We have sent FS and TS for approval. We have received Security Approval.

**Comment by Sathraja-Beez** [comment]
Demo scheduled for tommorow (26 April)

**Comment by Sathraja-Beez** [comment]
Requested them to test and waiting for the feedback

**Comment by koushik-ac** [comment]
Received UAT Approval. Waiting for FS Approval from Luciano. Rest all activities are completed.

**Comment by mbm-hub** [comment]
Is LIVE
