### ISSUE TITLE
Tesco Enhancement

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/automation-dev#67]
Tesco Enhancement has been completed and we are waiting for an UAT Signoff from Customer

**Comment by karthikeyan23** [comment]
pending with customer on UAT completion

**Comment by Dean13b** [comment]
External dependency : Portal credential to be reset

**Comment by koushik-ac** [comment]
UAT sign-off has been received.

**Comment by Dean13b** [comment]
Dependency with Carrefour enhancement

**Comment by Dean13b** [comment]
Next execution on 10th of October 2023
