### ISSUE TITLE
Employee Expenses

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#7]
Consultant: Koushik

Documentation:
https://azurebeezlabs.sharepoint.com/:w:/s/BeezLabsFactory/EcVZWnqoqaJPgVi3AAXPN-sBUCciutZYe1Xnh1d6mXgFdQ?e=qCFpFj

**Comment by mbm-hub** [comment]
Juan's feedback is covered and tested. We will share the test results by Jan 3 and target for go-live on 4th Jan Wednesday (SAP movement is required)

**Comment by mbm-hub** [comment]
Issues with Email service @kruthik-nivas is looking it

**Comment by kruthik-nivas** [comment]
@mbm-hub I have found what went wrong in email service, a small validation must be done and i have implemented that , i will test this once from end to end and once after @karthikeyan23  is free we will deploy it in dev tulip.onebacardi  and let others knwo via development and issues channel

**Comment by kruthik-nivas** [comment]
@mbm-hub I have tested the email issue it sending fine now

**Comment by mbm-hub** [comment]
Following up for TR import with BASIS as on March 27

**Comment by Sathraja-Beez** [comment]
Getting final UAT approval by End of Today (25 April)and then target the TR movement window for tomorrow.
