### ISSUE TITLE
Canada Crawlers Issue

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/automation-dev#79]
Customer has raised some concerns during review of data we have provided after the fixes that we done during last week. Creating this issue to check on this.

**Comment by Dean13b** [comment]
Sakthi to connect with customer to proceed further

**Comment by koushik-ac** [comment]
Clarification pending with End User for Name Format for the file. Confirmation for other issues is still pending.

**Comment by Sakthi1502** [comment]
Client has responded that everything is fine as of now. So closing this issue.
