### ISSUE TITLE
Crawler Support Issues

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/automation-dev#82]

**Comment by koushik-ac** [comment]
Work in Progress with the Issues.

**Comment by Dean13b** [comment]
@SanthoshKumar2220  has completed his portion

**Comment by Dean13b** [comment]
@NaveenKumarD8 , 4/7 has bee completed.

**Comment by Dean13b** [comment]
6/7 has been completed

**Comment by Sakthi1502** [comment]
Update: MumbaiDutyfree has been identified as an enhancement since there is a change in url as well as UI of the website.

**Comment by Sakthi1502** [comment]
Update: Costco issue is pending and is being worked on by Naveen.

**Comment by Sakthi1502** [comment]
@NaveenKumarD8 to provide an update whether Costco issue is fixed and testing completed

**Comment by Sakthi1502** [comment]
@NaveenKumarD8 Provide an update here once Costco is tested. If you face any delays, update it here. I can help.

**Comment by NaveenKumarD8** [comment]
Costco is tested Multiple times in Tulip Working Fine, Issue is Completed.

**Comment by Sakthi1502** [comment]
Production run for Costco to happen today. Will check if everything goes fine and close this issue.

**Comment by Sakthi1502** [comment]
Costco failed again during Production run. Need to check on this.

**Comment by Sakthi1502** [comment]
Creating separate issue for Costco Failure Scenario since it is parked. Closing this issue.
