### ISSUE TITLE
Constant Contact Email List

### ISSUE THREAD

**Issue by mbm-hub** [beezlabs-org/automation-dev#9]
Consultant: Koushik

Documentation:
https://azurebeezlabs.sharepoint.com/:w:/s/BeezLabsFactory/EbIV0ihlTCpCkP9DYOFTSskBifdlIJbnupjLEwrogspngg?e=9Oht6o

**Comment by mbm-hub** [comment]
Email attachment is corrupted and this issue is being analysed. Being done by @Rupsa96

**Comment by mbm-hub** [comment]
Dependency:
AD Integration for email
User account for Constant Contact
@mbm-hub to resolve

**Comment by mbm-hub** [comment]
Email attachment issue is resolved.

**Comment by Sathraja-Beez** [comment]
we are receiving different email format from azure , requested user to change the format  ….testing is yet to done as we didn't get the format from them

**Comment by mbm-hub** [comment]
Discussion on MFA is on-going with customer. We proposed OKTA authenticator from our end, but it is being still considered as a viable option or not from customer side. Awaiting more inputs.

**Comment by mbm-hub** [comment]
Have a checkpoint of 22-Feb for Rupsa's comeback. 24-Feb should be the planned go-live date, no change in it.

**Comment by mbm-hub** [comment]
Constant Contact email attachment bot is failing. @kruthik-nivas to check with @koushik-ac

**Comment by mbm-hub** [comment]
Use case is LIVE
